<?php
declare(strict_types=1);

// ColoradoInformationMarketplace SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

ColoradoInformationMarketplaceUtility::setRegistrar(function (ColoradoInformationMarketplaceUtility $u): void {
    $u->clean = [ColoradoInformationMarketplaceClean::class, 'call'];
    $u->done = [ColoradoInformationMarketplaceDone::class, 'call'];
    $u->make_error = [ColoradoInformationMarketplaceMakeError::class, 'call'];
    $u->feature_add = [ColoradoInformationMarketplaceFeatureAdd::class, 'call'];
    $u->feature_hook = [ColoradoInformationMarketplaceFeatureHook::class, 'call'];
    $u->feature_init = [ColoradoInformationMarketplaceFeatureInit::class, 'call'];
    $u->fetcher = [ColoradoInformationMarketplaceFetcher::class, 'call'];
    $u->make_fetch_def = [ColoradoInformationMarketplaceMakeFetchDef::class, 'call'];
    $u->make_context = [ColoradoInformationMarketplaceMakeContext::class, 'call'];
    $u->make_options = [ColoradoInformationMarketplaceMakeOptions::class, 'call'];
    $u->make_request = [ColoradoInformationMarketplaceMakeRequest::class, 'call'];
    $u->make_response = [ColoradoInformationMarketplaceMakeResponse::class, 'call'];
    $u->make_result = [ColoradoInformationMarketplaceMakeResult::class, 'call'];
    $u->make_point = [ColoradoInformationMarketplaceMakePoint::class, 'call'];
    $u->make_spec = [ColoradoInformationMarketplaceMakeSpec::class, 'call'];
    $u->make_url = [ColoradoInformationMarketplaceMakeUrl::class, 'call'];
    $u->param = [ColoradoInformationMarketplaceParam::class, 'call'];
    $u->prepare_auth = [ColoradoInformationMarketplacePrepareAuth::class, 'call'];
    $u->prepare_body = [ColoradoInformationMarketplacePrepareBody::class, 'call'];
    $u->prepare_headers = [ColoradoInformationMarketplacePrepareHeaders::class, 'call'];
    $u->prepare_method = [ColoradoInformationMarketplacePrepareMethod::class, 'call'];
    $u->prepare_params = [ColoradoInformationMarketplacePrepareParams::class, 'call'];
    $u->prepare_path = [ColoradoInformationMarketplacePreparePath::class, 'call'];
    $u->prepare_query = [ColoradoInformationMarketplacePrepareQuery::class, 'call'];
    $u->graphql_body = [ColoradoInformationMarketplaceGraphql::class, 'body'];
    $u->graphql_errors = [ColoradoInformationMarketplaceGraphql::class, 'errors'];
    $u->result_basic = [ColoradoInformationMarketplaceResultBasic::class, 'call'];
    $u->result_body = [ColoradoInformationMarketplaceResultBody::class, 'call'];
    $u->result_headers = [ColoradoInformationMarketplaceResultHeaders::class, 'call'];
    $u->transform_request = [ColoradoInformationMarketplaceTransformRequest::class, 'call'];
    $u->transform_response = [ColoradoInformationMarketplaceTransformResponse::class, 'call'];
});
